# Generated by Django 4.2.5 on 2023-10-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_at',
        ),
    ]
